name: CI

on:
  push:
    branches:
      - 3.x
      - 3.next
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  testsuite-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2']
        db-type: [mysql, pgsql, sqlite]
        prefer-lowest: ['']
        include:
          - php-version: '8.1'
            db-type: 'sqlite'
            prefer-lowest: 'prefer-lowest'

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pg-password
          POSTGRES_DB: cakephp_test

    steps:
      - uses: actions/checkout@v3

      - name: Setup MySQL
        if: matrix.db-type == 'mysql'
        run: |
          sudo service mysql start
          mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE cakephp_test DEFAULT COLLATE=utf8mb4_general_ci;'
          mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE cakephp_comparisons;'
          mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE cakephp_snapshot;'

      - name: Setup Postgres
        if: matrix.db-type == 'pgsql'
        run: |
          export PGPASSWORD='pg-password'
          psql -h 127.0.0.1 -U postgres -c 'CREATE DATABASE "cakephp_snapshot";'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_${{ matrix.db-type }}
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Get date part for cache key
        id: key-date
        run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-${{ matrix.prefer-lowest }}

      - name: Composer install
        run: |
          if [[ ${{ matrix.php-version }} == '8.2' ]]; then
            composer install --ignore-platform-req=php
          elif ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then
            composer update --prefer-lowest --prefer-stable
          else
            composer update
          fi

      - name: Run PHPUnit
        run: |
          if [[ ${{ matrix.db-type }} == 'sqlite' ]]; then
            export DB='sqlite'
          fi
          if [[ ${{ matrix.db-type }} == 'mysql' ]]; then
            export DB='mysql'
            export DB_URL='mysql://root:root@127.0.0.1/cakephp_test'
            export DB_URL_COMPARE='mysql://root:root@127.0.0.1/cakephp_comparisons'
            export DB_URL_SNAPSHOT='mysql://root:root@127.0.0.1/cakephp_snapshot'
          fi
          if [[ ${{ matrix.db-type }} == 'pgsql' ]]; then
            export DB='pgsql'
            export DB_URL='postgres://postgres:pg-password@127.0.0.1/cakephp_test'
            export DB_URL_SNAPSHOT='postgres://postgres:pg-password@127.0.0.1/cakephp_snapshot'
          fi
          if [[ ${{ matrix.php-version }} == '8.1' && ${{ matrix.db-type }} == 'mysql' ]]; then
            vendor/bin/phpunit --coverage-clover=coverage.xml
          else
            vendor/bin/phpunit
          fi

      - name: Code Coverage Report
        if: success() && matrix.php-version == '8.1' && matrix.db-type == 'mysql'
        uses: codecov/codecov-action@v3

  cs-stan:
    uses: cakephp/.github/.github/workflows/cs-stan.yml@5.x
    secrets: inherit
